export interface Book {
  id: number;
  title: string;
  author: string;
  coverImage: string;
  year: number;
  rating: number;
  publisher: string;
  isbn: string;
  pages: number;
  subject: string;
  description: string;
  country: "Bangladesh" | "India" | "Pakistan";
}

// export const sampleBooks: Book[] = [
//   {
//     id: 1,
//     title: "A Golden Age",
//     author: "Tahmima Anam",
//     coverImage: "/api/placeholder/180/270",
//     year: 2007,
//     rating: 4.2,
//     publisher: "HarperCollins",
//     isbn: "978-0-06-147875-7",
//     pages: 288,
//     subject: "Historical Fiction",
//     description: "A story set during the Bangladesh Liberation War of 1971",
//     country: "Bangladesh"
//   },
//   {
//     id: 2,
//     title: "Lajja",
//     author: "Taslima Nasrin",
//     coverImage: "/api/placeholder/180/270",
//     year: 1993,
//     rating: 4.1,
//     publisher: "Penguin Books",
//     isbn: "978-0-14-024051-5",
//     pages: 216,
//     subject: "Fiction",
//     description: "A powerful novel about religious tensions in Bangladesh",
//     country: "Bangladesh"
//   },
//   {
//     id: 3,
//     title: "The Good Muslim",
//     author: "Tahmima Anam",
//     coverImage: "/api/placeholder/180/270",
//     year: 2011,
//     rating: 3.9,
//     publisher: "HarperCollins",
//     isbn: "978-0-06-147876-4",
//     pages: 304,
//     subject: "Historical Fiction",
//     description: "The aftermath of Bangladesh's war of independence",
//     country: "Bangladesh"
//   },
//   {
//     id: 4,
//     title: "Selected Poems",
//     author: "Kazi Nazrul Islam",
//     coverImage: "/api/placeholder/180/270",
//     year: 1999,
//     rating: 4.7,
//     publisher: "Bangla Academy",
//     isbn: "978-984-07-4254-8",
//     pages: 186,
//     subject: "Poetry",
//     description: "Collection of revolutionary poems by Bangladesh's national poet",
//     country: "Bangladesh"
//   },
//   {
//     id: 5,
//     title: "The Midnight's Children",
//     author: "Salman Rushdie",
//     coverImage: "/api/placeholder/180/270",
//     year: 1981,
//     rating: 4.3,
//     publisher: "Jonathan Cape",
//     isbn: "978-0-224-01823-0",
//     pages: 446,
//     subject: "Magical Realism",
//     description: "Children born at the midnight hour of India's independence",
//     country: "India"
//   },
//   {
//     id: 6,
//     title: "The God of Small Things",
//     author: "Arundhati Roy",
//     coverImage: "/api/placeholder/180/270",
//     year: 1997,
//     rating: 4.1,
//     publisher: "IndiaInk",
//     isbn: "978-0-679-45731-2",
//     pages: 340,
//     subject: "Fiction",
//     description: "A story about the childhood experiences of fraternal twins",
//     country: "India"
//   },
//   {
//     id: 7,
//     title: "A Suitable Boy",
//     author: "Vikram Seth",
//     coverImage: "/api/placeholder/180/270",
//     year: 1993,
//     rating: 4.4,
//     publisher: "Phoenix House",
//     isbn: "978-1-85799-943-8",
//     pages: 1488,
//     subject: "Fiction",
//     description: "A coming-of-age story set in post-independence India",
//     country: "India"
//   },
//   {
//     id: 8,
//     title: "The White Tiger",
//     author: "Aravind Adiga",
//     coverImage: "/api/placeholder/180/270",
//     year: 2008,
//     rating: 3.9,
//     publisher: "Free Press",
//     isbn: "978-1-4165-6259-7",
//     pages: 304,
//     subject: "Fiction",
//     description: "A tale of ambition and corruption in modern India",
//     country: "India"
//   },
//   {
//     id: 9,
//     title: "Train to Pakistan",
//     author: "Khushwant Singh",
//     coverImage: "/api/placeholder/180/270",
//     year: 1956,
//     rating: 4.2,
//     publisher: "Chatto & Windus",
//     isbn: "978-0-8070-5870-3",
//     pages: 192,
//     subject: "Historical Fiction",
//     description: "A novel about the Partition of India in 1947",
//     country: "India"
//   },
//   {
//     id: 10,
//     title: "Moth Smoke",
//     author: "Mohsin Hamid",
//     coverImage: "/api/placeholder/180/270",
//     year: 2000,
//     rating: 3.8,
//     publisher: "Farrar, Straus and Giroux",
//     isbn: "978-0-374-21354-2",
//     pages: 256,
//     subject: "Fiction",
//     description: "A tale of love, drugs, and class conflict in Lahore",
//     country: "Pakistan"
//   },
//   {
//     id: 11,
//     title: "The Reluctant Fundamentalist",
//     author: "Mohsin Hamid",
//     coverImage: "/api/placeholder/180/270",
//     year: 2007,
//     rating: 3.7,
//     publisher: "Hamish Hamilton",
//     isbn: "978-0-241-14365-2",
//     pages: 184,
//     subject: "Fiction",
//     description: "A Pakistani man's experience in America after 9/11",
//     country: "Pakistan"
//   },
//   {
//     id: 12,
//     title: "Ice Candy Man",
//     author: "Bapsi Sidhwa",
//     coverImage: "/api/placeholder/180/270",
//     year: 1988,
//     rating: 4.0,
//     publisher: "William Heinemann Ltd",
//     isbn: "978-0-434-70120-3",
//     pages: 278,
//     subject: "Historical Fiction",
//     description: "A story set during the Partition of India, seen through a child's eyes",
//     country: "Pakistan"
//   },
//   {
//     id: 13,
//     title: "The Shadow Lines",
//     author: "Amitav Ghosh",
//     coverImage: "/api/placeholder/180/270",
//     year: 1988,
//     rating: 4.3,
//     publisher: "Ravi Dayal Publishers",
//     isbn: "978-0-7011-3168-7",
//     pages: 246,
//     subject: "Fiction",
//     description: "A novel exploring borders and nationalism in the Indian subcontinent",
//     country: "India"
//   },
//   {
//     id: 14,
//     title: "River of Fire",
//     author: "Qurratulain Hyder",
//     coverImage: "/api/placeholder/180/270",
//     year: 1959,
//     rating: 4.4,
//     publisher: "New Directions",
//     isbn: "978-0-8112-1459-5",
//     pages: 428,
//     subject: "Historical Fiction",
//     description: "An epic tale spanning two thousand years of Indian history",
//     country: "India"
//   },
//   {
//     id: 15,
//     title: "Home Fire",
//     author: "Kamila Shamsie",
//     coverImage: "/api/placeholder/180/270",
//     year: 2017,
//     rating: 4.1,
//     publisher: "Riverhead Books",
//     isbn: "978-0-7352-1769-7",
//     pages: 288,
//     subject: "Fiction",
//     description: "A contemporary reimagining of Sophocles's Antigone",
//     country: "Pakistan"
//   },
//   {
//     id: 16,
//     title: "Season of the Rainbirds",
//     author: "Nadeem Aslam",
//     coverImage: "/api/placeholder/180/270",
//     year: 1993,
//     rating: 3.9,
//     publisher: "Andre Deutsch",
//     isbn: "978-0-233-98771-4",
//     pages: 192,
//     subject: "Fiction",
//     description: "A mysterious story set in a small Pakistani town",
//     country: "Pakistan"
//   },
//   {
//     id: 17,
//     title: "Interpreter of Maladies",
//     author: "Jhumpa Lahiri",
//     coverImage: "/api/placeholder/180/270",
//     year: 1999,
//     rating: 4.3,
//     publisher: "Mariner Books",
//     isbn: "978-0-395-92720-5",
//     pages: 198,
//     subject: "Short Stories",
//     description: "Stories about the lives of Indians and Indian Americans",
//     country: "India"
//   },
//   {
//     id: 18,
//     title: "Kartography",
//     author: "Kamila Shamsie",
//     coverImage: "/api/placeholder/180/270",
//     year: 2002,
//     rating: 4.0,
//     publisher: "Bloomsbury",
//     isbn: "978-0-7475-6155-6",
//     pages: 342,
//     subject: "Fiction",
//     description: "A love story set against the backdrop of Karachi's violence",
//     country: "Pakistan"
//   },
//   {
//     id: 19,
//     title: "The Boat People",
//     author: "Sharon Bala",
//     coverImage: "/api/placeholder/180/270",
//     year: 2018,
//     rating: 4.2,
//     publisher: "McClelland & Stewart",
//     isbn: "978-0-7710-2731-1",
//     pages: 352,
//     subject: "Fiction",
//     description: "A novel about Tamil refugees fleeing Sri Lanka and arriving in Canada",
//     country: "Bangladesh"
//   },
//   {
//     id: 20,
//     title: "The Association of Small Bombs",
//     author: "Karan Mahajan",
//     coverImage: "/api/placeholder/180/270",
//     year: 2016,
//     rating: 3.8,
//     publisher: "Viking",
//     isbn: "978-0-525-42963-9",
//     pages: 276,
//     subject: "Fiction",
//     description: "A novel examining the aftermath of a bomb in a Delhi marketplace",
//     country: "India"
//   }
// ];

export const sampleBooks: Book[] = [
  {
    id: 1,
    title: "Himu Mama",
    author: "Humayun Ahmed",
    coverImage:
      "https://test.atlantisdecora.com/public/products/prod-1246233.04F72C25.jpg",
    year: 2000,
    rating: 4.8,
    publisher: "Bangla Prokashani",
    isbn: "978-1-234-56789-0",
    pages: 250,
    subject: "Fiction",
    description: "A story about Himu and his unique adventures.",
    country: "Bangladesh",
  },
  {
    id: 2,
    title: "Amar Bondhu Rashed",
    author: "Muhammad Zafar Iqbal",
    coverImage:
      "https://boibichitra.com/public/uploads/products/meta/I7dtZZ9l11QNNSoLTG6GtNuR6ktwHAyVGzLGzM0y.jpeg",
    year: 2005,
    rating: 4.9,
    publisher: "Shomoy Publications",
    isbn: "978-0-987-65432-1",
    pages: 300,
    subject: "Fiction",
    description: "A novel that portrays the friendship of two schoolboys.",
    country: "Bangladesh",
  },
  {
    id: 3,
    title: "Hangor Nodi Grenade",
    author: "Selina Hossain",
    coverImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3f3B9lZb_1o4mcaYEUDjO8HOXuUUto1Xy9g&s",
    year: 2010,
    rating: 4.7,
    publisher: "Prothoma Prokashon",
    isbn: "978-1-543-98201-5",
    pages: 350,
    subject: "Historical Fiction",
    description: "A novel set during the 1971 Liberation War of Bangladesh.",
    country: "Bangladesh",
  },
  {
    id: 4,
    title: "Ma",
    author: "Anisul Hoque",
    coverImage:
      "https://upload.wikimedia.org/wikipedia/en/thumb/c/c0/The_cover_image_of_Maa.jpg/220px-The_cover_image_of_Maa.jpg",
    year: 2012,
    rating: 4.8,
    publisher: "Oxford University Press",
    isbn: "978-0-001-23987-4",
    pages: 280,
    subject: "Fiction",
    description: "A story exploring the bond between a mother and her child.",
    country: "Bangladesh",
  },
  {
    id: 5,
    title: "Noorjahan",
    author: "Imdadul Haq Milon",
    coverImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQK6BdOF9QxH2jn3zYPbiUJZOg1lToWyHtUAA&s",
    year: 1998,
    rating: 4.6,
    publisher: "Rupa & Co.",
    isbn: "978-0-774-12987-9",
    pages: 270,
    subject: "Fiction",
    description: "A historical fiction novel about the legendary Noorjahan.",
    country: "Bangladesh",
  },
  {
    id: 6,
    title: "Nishiddho Loban",
    author: "Syed Shamsul Haq",
    coverImage:
      "https://bengaliebook.com/wp-content/uploads/2022/04/%E0%A6%A8%E0%A6%BF%E0%A6%B7%E0%A6%BF%E0%A6%A6%E0%A7%8D%E0%A6%A7-%E0%A6%B2%E0%A7%8B%E0%A6%AC%E0%A6%BE%E0%A6%A8-724x1024.jpg",
    year: 1995,
    rating: 4.7,
    publisher: "Samsad Prokashoni",
    isbn: "978-0-558-29342-4",
    pages: 320,
    subject: "Fiction",
    description: "A story that delves into the forbidden and the mystical.",
    country: "Bangladesh",
  },
  {
    id: 7,
    title: "Kothao Keu Nei",
    author: "Ahsan Habib",
    coverImage:
      "https://m.media-amazon.com/images/M/MV5BMmVkYjdjOTEtMDA2NC00NzYwLTg1NjEtZTdkOTE0ZTU0M2I2XkEyXkFqcGc@._V1_.jpg",
    year: 2008,
    rating: 4.5,
    publisher: "Bengal Publications",
    isbn: "978-0-669-87454-3",
    pages: 220,
    subject: "Fiction",
    description: "A story of loneliness and discovery in a small town.",
    country: "Bangladesh",
  },
  {
    id: 8,
    title: "Janani",
    author: "Shawkat Osman",
    coverImage: "https://fs.pbs.com.bd/DIR/Com/PBS/Product/Image/1811242.jpg",
    year: 1987,
    rating: 4.6,
    publisher: "Rochona Prokashoni",
    isbn: "978-0-467-31234-8",
    pages: 200,
    subject: "Fiction",
    description: "A poignant exploration of motherhood.",
    country: "Bangladesh",
  },
  {
    id: 9,
    title: "Shanchita",
    author: "Kazi Nazrul Islam",
    coverImage:
      "https://atlantisdecora.com/public/products/20221213051234Ji0khO.webp",
    year: 1960,
    rating: 4.9,
    publisher: "Bangla Academy",
    isbn: "978-1-213-80973-1",
    pages: 150,
    subject: "Poetry",
    description: "A collection of poems by the national poet of Bangladesh.",
    country: "Bangladesh",
  },
  {
    id: 10,
    title: "বিলবোর্ড",
    author: "Sadat Hossain",
    coverImage:
      "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/Billboard_-Sadat_Hossain_-f6fb3-459830.jpg",
    year: 2020,
    rating: 3.0,
    publisher: "Adarsha Prokashani",
    isbn: "978-0-561-26754-2",
    pages: 180,
    subject: "Fiction",
    description: "A modern story about the world of advertising.",
    country: "Bangladesh",
  },
  {
    id: 11,
    title: "জ্যোৎস্নায় বর্ষার মেঘ",
    author: "Sabrina Jahan Shomi",
    coverImage:
      "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/Josnai_Borsar_Megh-Sabrina_Jahan_Shomi-5550b-459685.png",
    year: 2019,
    rating: 3.0,
    publisher: "Bengali Books",
    isbn: "978-1-292-87643-0",
    pages: 220,
    subject: "Romantic Fiction",
    description: "A love story set during the rainy season.",
    country: "Bangladesh",
  },
  {
    id: 12,
    title: "কীভাবে গড়বেন নেক সন্তান",
    author: "M Badrul Islam Bin Harun",
    coverImage:
      "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/Kivabe_Gorben_Nek_Sontan-M_Badrul_Islam_Bin_Harun-944c2-459672.jpg",
    year: 2018,
    rating: 2.0,
    publisher: "Islamic Publications",
    isbn: "978-0-923-74635-5",
    pages: 160,
    subject: "Religion",
    description: "A guide to raising virtuous children.",
    country: "Bangladesh",
  },
  {
    id: 13,
    title: "বাস্তবতার আয়নায়",
    author: "Shakir Mahmud Safat",
    coverImage:
      "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/Bastobotar_Aynay-Shakir_Mahmud_Safat-889f4-459646.png",
    year: 2021,
    rating: 4.0,
    publisher: "Not Available",
    isbn: "Not Available",
    pages: 180,
    subject: "Philosophy",
    description: "A philosophical exploration of reality.",
    country: "Bangladesh",
  },
  {
    id: 14,
    title: "ফুটনোট",
    author: "Roddur Aritro",
    coverImage:
      "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/Footnote-Roddur_Aritro-657d2-459541.jpg",
    year: 2020,
    rating: 4.0,
    publisher: "Not Available",
    isbn: "Not Available",
    pages: 190,
    subject: "Non-Fiction",
    description: "A non-fiction book filled with insightful thoughts.",
    country: "Bangladesh",
  },
  {
    id: 15,
    title: "নারীর শত্রু-মিত্র",
    author: "Muhammad Jainul Abidin",
    coverImage:
      "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/Narir_Shotru_Mitro_-Muhammod_Jainul_Abidin-cfcf7-459506.jpg",
    year: 2019,
    rating: 5.0,
    publisher: "Sahitya Prokash",
    isbn: "978-0-645-29301-7",
    pages: 210,
    subject: "Women's Studies",
    description: "A comprehensive book on women's struggles and triumphs.",
    country: "Bangladesh",
  },
  {
    id: 16,
    title: "দু’আ-ই রসূল",
    author: "Muslim Bangla Foundation",
    coverImage:
      "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/Dua_i_Rasul-Muslim_Bangla_Foundation-dbf73-459489.jpg",
    year: 2015,
    rating: 2.0,
    publisher: "Not Available",
    isbn: "Not Available",
    pages: 180,
    subject: "Religion",
    description: "A book on the prayers of the Prophet Muhammad.",
    country: "Bangladesh",
  },
  {
    id: 17,
    title: "নিত্যদিন শত হাদীস",
    author: "Mohajatok",
    coverImage:
      "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/Nittodin_Shoto_Hadis-Mohajatok_-32431-459425.jpg",
    year: 2017,
    rating: 3.0,
    publisher: "Not Available",
    isbn: "Not Available",
    pages: 200,
    subject: "Religion",
    description: "A collection of daily hadiths.",
    country: "Bangladesh",
  },
  {
    id: 18,
    title: "ফ্রেশ স্টেশনারি ‘গল্পের খাতা’ ভলিউম-২",
    author: "Sahityodesh",
    coverImage:
      "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/Fresh_Stationery_Golper_Khata_Vol_2-Sahityodesh_-4f1e7-459149.jpg",
    year: 2020,
    rating: 5.0,
    publisher: "Sahityodesh Publications",
    isbn: "978-1-019-45578-1",
    pages: 210,
    subject: "Fiction",
    description: "A collection of short stories for young readers.",
    country: "Bangladesh",
  },
  {
    id: 19,
    title: "স্কুল/মাদরাসা/হোম-স্কুলিং প্যাকেজ",
    author: "Jahid Hasan",
    coverImage:
      "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/School_Madrasah_Home_Schooling_package-Jahid_Hasan-50d87-459104.jpg",
    year: 2020,
    rating: 2.0,
    publisher: "Not Available",
    isbn: "Not Available",
    pages: 230,
    subject: "Education",
    description: "A guide to homeschooling and madrasa education.",
    country: "Bangladesh",
  },
  {
    id: 20,
    title: "নক্সী কাঁথার মাঠ",
    author: "Jashimuddin",
    coverImage:
      "https://ds.rokomari.store/rokomari110/ProductNew20190903/260X372/ea0da9808774_30285.gif",
    year: 1971,
    rating: 4.7,
    publisher: "Kotha Prokash",
    isbn: "978-1-209-87654-3",
    pages: 300,
    subject: "Historical Fiction",
    description:
      "A historical novel based on the 1971 Liberation War of Bangladesh.",
    country: "Bangladesh",
  },
];
